# Generated by Django 4.1.3 on 2022-11-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_item',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='menu_item',
            old_name='cuisine_id',
            new_name='cuisine',
        ),
    ]
