# Generated by Django 4.1.3 on 2022-11-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_item_spice_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='spice_level',
            field=models.CharField(choices=[(' ', ' '), ('🌶️', '🌶️'), ('🌶️🌶️', '🌶️🌶️'), ('🌶️🌶️🌶️', '🌶️🌶️🌶️'), ('🌶️🌶️🌶️🌶️', '🌶️🌶️🌶️🌶️'), ('🌶️🌶️🌶️🌶️🌶️', '🌶️🌶️🌶️🌶️🌶️')], default=' ', max_length=12),
        ),
    ]
